# shellcheck shell=bash

export TMUX_POWERLINE_THEME="tabs-only"
export TMUX_POWERLINE_DIR_USER_THEMES="${XDG_CONFIG_HOME:-$HOME/.config}/tmux-powerline/themes"
export TMUX_POWERLINE_DIR_USER_SEGMENTS="${XDG_CONFIG_HOME:-$HOME/.config}/tmux-powerline/segments"

export TMUX_POWERLINE_STATUS_VISIBILITY="on"
export TMUX_POWERLINE_STATUS_INTERVAL=30
export TMUX_POWERLINE_STATUS_JUSTIFICATION="left"
export TMUX_POWERLINE_STATUS_STYLE="fg=#cecdc3,bg=#1c1b1a,align=centre"
export TMUX_POWERLINE_STATUS_LEFT_LENGTH=0
export TMUX_POWERLINE_STATUS_RIGHT_LENGTH=42
export TMUX_POWERLINE_WINDOW_STATUS_SEPARATOR=""
