#!/usr/bin/env bash

# -- Icon Glyphs (Nerd Font) --
ICON_CLOCK=
ICON_CHEVRON=
ICON_VOLUME_HIGH=󰕾
ICON_VOLUME_MED=󰖀
ICON_VOLUME_LOW=󰕿
ICON_VOLUME_MUTE=󰖁
ICON_BATTERY_100=
ICON_BATTERY_75=
ICON_BATTERY_50=
ICON_BATTERY_25=
ICON_BATTERY_LOW=
ICON_BATTERY_CHARGING=
ICON_MERGE=
ICON_SLACK=󰒱
ICON_SLIDER_KNOB=󰝥

# -- Weather Icons (nf-weather-*) --
ICON_WEATHER_SUNNY=
ICON_WEATHER_CLEAR_NIGHT=
ICON_WEATHER_PARTLY_CLOUDY=
ICON_WEATHER_PARTLY_CLOUDY_NIGHT=
ICON_WEATHER_CLOUDY=
ICON_WEATHER_OVERCAST=
ICON_WEATHER_FOG=
ICON_WEATHER_DRIZZLE=
ICON_WEATHER_RAIN=
ICON_WEATHER_HEAVY_RAIN=
ICON_WEATHER_SNOW=
ICON_WEATHER_HEAVY_SNOW=
ICON_WEATHER_SLEET=
ICON_WEATHER_HAIL=
ICON_WEATHER_THUNDER=
ICON_WEATHER_WINDY=
