#!/usr/bin/env bash

# -- Icon Glyphs (Nerd Font) --
ICON_CLOCK=
ICON_CHEVRON=
ICON_VOLUME_HIGH=󰕾
ICON_VOLUME_MED=󰖀
ICON_VOLUME_LOW=󰕿
ICON_VOLUME_MUTE=󰖁
ICON_BATTERY_100=
ICON_BATTERY_75=
ICON_BATTERY_50=
ICON_BATTERY_25=
ICON_BATTERY_LOW=
ICON_BATTERY_CHARGING=
ICON_MERGE=
ICON_SLACK=󰒱
ICON_SLIDER_KNOB=󰝥
