#!/usr/bin/env bash

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"
FONT="JetBrainsMono Nerd Font"

source "$CONFIG_DIR/colors.sh"
source "$CONFIG_DIR/icons.sh"

##### Bar Appearance #####
sketchybar --bar position=top height=40 blur_radius=30 color=$COLOR_BAR_BG

##### Changing Defaults #####
default=(
  padding_left=5
  padding_right=5
  icon.font="$FONT:Bold:17.0"
  label.font="$FONT:Bold:14.0"
  icon.color=$COLOR_WHITE
  label.color=$COLOR_WHITE
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

##### Left Items #####
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

##### Right Items #####
source "$ITEM_DIR/slack.sh"
source "$ITEM_DIR/clock.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/merge_queue.sh"

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
